### ISSUE TITLE
Link at bottom of LearnMore page may be wrong

### ISSUE THREAD

**Issue by PaulMEdwards** [Lambda-School-Labs/memefly-fe#55]
I suspect that the link at the bottom of the [LearnMore](https://www.memeflyai.com/LearnMore) page which reads "www.MemeFlyAi.com" but navigates to "https://material-ui.com/" may not be as desired.

**Comment by LindseyCason** [comment]
Fixed! Thank you!

**Comment by PaulMEdwards** [comment]
I'm not seeing the fix deployed to the production site, @LindseyCason ...
